// Bundle the pinned reader and WASM bytes into one local script. Supplying
// wasmBinary avoids CDN requests and works under file:// without fetch/CORS.
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const pkg = path.join(root, 'node_modules/zxing-wasm');
const version = JSON.parse(fs.readFileSync(path.join(pkg, 'package.json'))).version;
const script = fs.readFileSync(path.join(pkg, 'dist/iife/reader/index.js'), 'utf8');
const base64 = fs.readFileSync(path.join(pkg, 'dist/reader/zxing_reader.wasm')).toString('base64');
fs.writeFileSync(path.join(root, 'vendor/zxing-reader.js'),
  '// Generated by scripts/vendor-zxing.cjs from zxing-wasm ' + version + '.\n' +
  '// Wrapper: MIT; ZXing-C++: Apache-2.0. See vendor/NOTICE.md.\n' + script + '\n' +
  'ZXingWASM.prepareZXingModule({ overrides: { wasmBinary: Uint8Array.from(atob(' + JSON.stringify(base64) + '), function (c) { return c.charCodeAt(0); }) } });\n');
fs.copyFileSync(path.join(pkg, 'LICENSE'), path.join(root, 'vendor/zxing-wasm.LICENSE'));
console.log('Vendored zxing-wasm ' + version);
